# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-07 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
