# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20181207_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
